### ISSUE TITLE
Field Position Incorrect

### ISSUE THREAD

**Issue by NathanKuhn** [Seamonsters-2605/CompetitionBot2020#7]

**Comment by Trent1048** [comment]
Look into how `SuperHolonomicDrive` uses `direction` to factor in location tracking.

**Comment by Trent1048** [comment]
It is definitely a problem in `SuperHolonomicDrive`

**Comment by Trent1048** [comment]
Nope, it was actually just the wheels slipping on the carpet.

**Comment by Trent1048** [comment]
We need to take into account the weave of the carpet

**Comment by Trent1048** [comment]
The carpet issue is no longer relevant because carpet is not required.
